### ISSUE TITLE
Remove generation of gview images from vcf2core.pl script

### ISSUE THREAD

**Issue by apetkau** [apetkau/vcf2pseudoalignment#12]
Remove generation of gview images from vcf2core.pl script https://github.com/apetkau/vcf2pseudoalignment/blob/3de3e5737c3b93ef7b6ec7cdc20785973dbc47b7/vcf2core.pl.  This code is what's causing lots of delays when running this stage and we haven't found much use for these images.

**Comment by apetkau** [comment]
There's tests for this script in https://github.com/apetkau/vcf2pseudoalignment/blob/3de3e5737c3b93ef7b6ec7cdc20785973dbc47b7/t/vcf2core.t (may need to be re-written too).  @Takadonet may also be able to help you out since he was the original author.

**Comment by csieffert** [comment]
Generation of gview images has been removed from the core pipeline.
